# Change these first
owner: zgrossbart # Your GitHub organization or username, where this repository lives
repo: jdd-upptime # The name of this repository

sites:
  - name: JSONDiff
    url: https://www.jsondiff.com
    icon: https://jsondiff.com/favicon.ico
  - name: JSONDiff Base
    url: https://jsondiff.com
    icon: https://jsondiff.com/favicon.ico

assignees: # Users to assign downtime issues (optional)
  - zgrossbart

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /jdd-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: JSONDiff Upptime
  introTitle: "**JSONDiff.com** Upptime"
  introMessage: This is the uptime page for JSONDiff.com
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
